name: release build

on:
  release:
    types: [created] 

jobs:
  build-go-binary:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, windows, darwin, freebsd]
        goarch: [amd64, arm64, riscv64, ppc64le]
        exclude: 
          - goarch: riscv64
            goos: windows
          - goarch: riscv64
            goos: darwin
          - goarch: riscv64
            goos: freebsd
          - goarch: ppc64le
            goos: windows
          - goarch: ppc64le
            goos: darwin
          - goarch: ppc64le
            goos: freebsd
          - goarch: arm64
            goos: windows
          - goarch: arm64
            goos: windows

    steps:
      - uses: actions/checkout@v3
      - uses: wangyoucao577/go-release-action@v1.30
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} 
          goos: ${{ matrix.goos }}
          goarch: ${{ matrix.goarch }}
          goversion: 1.18 
          binary_name: "wasabi"